//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B1812282_VoNgocLong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENHNHAN
    {
        public string MABN { get; set; }
        public string TENBN { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public string DOITUONG { get; set; }
        public string DIENTHOAI { get; set; }
        public string DIACHI { get; set; }
    }
}
